### ISSUE TITLE
Adding a nonexistent dir to `sources` causes panics

### ISSUE THREAD

**Issue by zellyn** [cashapp/hermit#65]
Hermit `cd` hooks are active.

```
~/gh hermit --version
v0.2.8 (stable)
~/gh cat a2audit/bin/hermit.hcl 
sources = ["env:///hermit-packages", "https://github.com/cashapp/hermit-packages.git"]
~/gh ls a2audit/hermit-packages
ls: a2audit/hermit-packages: No such file or directory
~/gh cd a2audit/
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1478e15]

goroutine 1 [running]:
github.com/cashapp/hermit/app.Main.func3(0xc00023a100)
	/home/runner/work/hermit/hermit/app/main.go:91 +0x87
panic(0x1581be0, 0x19a1f90)
	/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:965 +0x1b9
github.com/alecthomas/kong.catch(0xc000173ad8)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/kong.go:383 +0xc5
panic(0x1581be0, 0x19a1f90)
	/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:965 +0x1b9
github.com/cashapp/hermit/sources.(*Sources).Bundles(0xc0002b0600, 0x7ffeefbfee90, 0x6, 0x1617a8f)
	/home/runner/work/hermit/hermit/sources/sources.go:147 +0x95
github.com/cashapp/hermit/manifest.(*Loader).Get(0xc0002b8570, 0x7ffeefbfee90, 0x6, 0x0, 0x0, 0x0)
	/home/runner/work/hermit/hermit/manifest/loader.go:70 +0x2ff
github.com/cashapp/hermit/manifest.(*Resolver).Resolve(0xc0002bc640, 0xc00023a100, 0x16d0f88, 0xc000185a80, 0x0, 0x80, 0xc000088000)
	/home/runner/work/hermit/hermit/manifest/resolver.go:270 +0x5e
github.com/cashapp/hermit.(*Env).Resolve(0xc0001ef570, 0xc00023a100, 0x16d0f88, 0xc000185a80, 0x0, 0x7ffeefbfee97, 0x6, 0xc00028dd20)
	/home/runner/work/hermit/hermit/env.go:568 +0x13e
github.com/cashapp/hermit/app.updateHermit(0xc00023a100, 0xc0001ef570, 0x7ffeefbfee90, 0xd, 0x1, 0x1)
	/home/runner/work/hermit/hermit/app/commands.go:467 +0x1c7
github.com/cashapp/hermit/app.(*execCmd).Run(0xc00015c1b0, 0xc00023a100, 0xc000133970, 0xc0001ef570, 0x0, 0x100d900, 0x0, 0x0)
	/home/runner/work/hermit/hermit/app/commands.go:427 +0xbfd
reflect.Value.call(0x1574420, 0xc00015c1b0, 0x213, 0x1617c03, 0x4, 0xc0002a4360, 0x4, 0x4, 0xc000173898, 0xc00010d3a8, ...)
	/opt/hostedtoolcache/go/1.16.5/x64/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x1574420, 0xc00015c1b0, 0x213, 0xc0002a4360, 0x4, 0x4, 0x2, 0x4, 0x14)
	/opt/hostedtoolcache/go/1.16.5/x64/src/reflect/value.go:337 +0xb9
github.com/alecthomas/kong.callMethod(0x16175f6, 0x3, 0x15a5e00, 0xc00015c1b0, 0x199, 0x1574420, 0xc00015c1b0, 0x213, 0xc0002a7e90, 0x40, ...)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/callbacks.go:71 +0x4ba
github.com/alecthomas/kong.(*Context).RunNode(0xc000185600, 0xc0001f48c0, 0xc000173ca8, 0x5, 0x5, 0x15a5d60, 0xc0001c97e0)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/context.go:706 +0x545
github.com/alecthomas/kong.(*Context).Run(0xc000185600, 0xc000173ca8, 0x5, 0x5, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/context.go:723 +0x99
github.com/cashapp/hermit/app.Main(0xc000218870, 0xf, 0x2, 0xc000222200, 0x3a, 0x1643350, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/hermit/hermit/app/main.go:177 +0xd0f
main.main()
	/home/runner/work/hermit/hermit/cmd/hermit/main.go:34 +0x338
~/gh/a2audit master *+ hermit -h
Usage: hermit <command>

🐚 Hermit is a hermetic binary package manager.

Flags:
  -h, --help            Show context-sensitive help.
      --version         Show version.
  -d, --debug           Enable debug logging.
  -t, --trace           Enable trace logging.
  -q, --quiet           Disable logging and progress UI, except fatal errors ($HERMIT_QUIET).
      --level=info      Set minimum log level ($HERMIT_LOG).
      --env=ENVARS      Extra environment variables to apply to environments.
      --short-prompt    Use a minimal prompt in active environments.

Environment:
  Commands for creating and managing environments.

  init    Initialise an environment (idempotent).

Global:
  Commands for interacting with the shared global Hermit state.

  version        Show version.
  validate       Check a package manifest source for errors.
  info           Show information on packages.
  shell-hooks    Manage Hermit auto-activation hooks of a shell.

Run "hermit <command> --help" for more information on a command.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1478e15]

goroutine 1 [running]:
github.com/cashapp/hermit/app.Main.func3(0xc0000a2180)
	/home/runner/work/hermit/hermit/app/main.go:91 +0x87
panic(0x1581be0, 0x19a1f90)
	/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:965 +0x1b9
github.com/alecthomas/kong.catch(0xc000173ad8)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/kong.go:383 +0xc5
panic(0x1581be0, 0x19a1f90)
	/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:965 +0x1b9
github.com/cashapp/hermit/sources.(*Sources).Bundles(0xc0002b06c0, 0x7ffeefbfee90, 0x6, 0x1617a8f)
	/home/runner/work/hermit/hermit/sources/sources.go:147 +0x95
github.com/cashapp/hermit/manifest.(*Loader).Get(0xc0002b8558, 0x7ffeefbfee90, 0x6, 0x0, 0x0, 0x0)
	/home/runner/work/hermit/hermit/manifest/loader.go:70 +0x2ff
github.com/cashapp/hermit/manifest.(*Resolver).Resolve(0xc0002bc640, 0xc0000a2180, 0x16d0f88, 0xc000185a80, 0x0, 0x80, 0xc000088000)
	/home/runner/work/hermit/hermit/manifest/resolver.go:270 +0x5e
github.com/cashapp/hermit.(*Env).Resolve(0xc0001ef570, 0xc0000a2180, 0x16d0f88, 0xc000185a80, 0x0, 0x7ffeefbfee97, 0x6, 0xc00028dd30)
	/home/runner/work/hermit/hermit/env.go:568 +0x13e
github.com/cashapp/hermit/app.updateHermit(0xc0000a2180, 0xc0001ef570, 0x7ffeefbfee90, 0xd, 0x1, 0x1)
	/home/runner/work/hermit/hermit/app/commands.go:467 +0x1c7
github.com/cashapp/hermit/app.(*execCmd).Run(0xc00015c1b0, 0xc0000a2180, 0xc0001338c0, 0xc0001ef570, 0x0, 0x100d900, 0x0, 0x0)
	/home/runner/work/hermit/hermit/app/commands.go:427 +0xbfd
reflect.Value.call(0x1574420, 0xc00015c1b0, 0x213, 0x1617c03, 0x4, 0xc0002a43c0, 0x4, 0x4, 0xc000173898, 0xc00010d718, ...)
	/opt/hostedtoolcache/go/1.16.5/x64/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x1574420, 0xc00015c1b0, 0x213, 0xc0002a43c0, 0x4, 0x4, 0x2, 0x4, 0x14)
	/opt/hostedtoolcache/go/1.16.5/x64/src/reflect/value.go:337 +0xb9
github.com/alecthomas/kong.callMethod(0x16175f6, 0x3, 0x15a5e00, 0xc00015c1b0, 0x199, 0x1574420, 0xc00015c1b0, 0x213, 0xc0002a7f50, 0x40, ...)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/callbacks.go:71 +0x4ba
github.com/alecthomas/kong.(*Context).RunNode(0xc000185600, 0xc0001f28c0, 0xc000173ca8, 0x5, 0x5, 0x15a5d60, 0xc0001c9830)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/context.go:706 +0x545
github.com/alecthomas/kong.(*Context).Run(0xc000185600, 0xc000173ca8, 0x5, 0x5, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/alecthomas/kong@v0.2.16/context.go:723 +0x99
github.com/cashapp/hermit/app.Main(0xc0000ae870, 0xf, 0x2, 0xc0000a8240, 0x3a, 0x1643350, 0x0, 0x0, 0x0, 0x0, ...)
	/home/runner/work/hermit/hermit/app/main.go:177 +0xd0f
main.main()
	/home/runner/work/hermit/hermit/cmd/hermit/main.go:34 +0x338
~/gh/a2audit master *+ 
```

**Comment by jvmakine** [comment]
Fix for this: https://github.com/cashapp/hermit/pull/67

**Comment by jvmakine** [comment]
Fix for this: https://github.com/cashapp/hermit/pull/67
